### ISSUE TITLE
Reduce permissions

### ISSUE THREAD

**Issue by lloyda** [cguZZman/plugin.onedrive#26]
This add on is asking for  create update and delete permissions on files in my OneDrive. This seems excessive. Cannot simply use read permission?

**Comment by cguZZman** [comment]
As you can see [here in the code in github](https://github.com/cguZZman/drive-login/blob/a10e651217079eb40d4bfbf21f6ab3094d0664ee/src/main/java/com/syncinator/kodi/login/oauth/provider/OneDriveProvider.java#L16), the addon only requires `offline_access, sites.read.all, files.read.all, user.read` permissions, which are read-only permissions. But you are correct, it's asking for full access for an unknown reason. Probably an issue from OneDrive side or because the `offline_access` permission. I will research on that.

**Comment by cguZZman** [comment]
Yeap, as suspected, it's an issue on the OneDrive side. Here is the link: https://github.com/OneDrive/onedrive-api-docs/issues/734
The scope `files.read.all` is showing the description as a full permission were asked, but this was not the case.
Anyway, good catch. Hope they fix the description soon.
