### ISSUE TITLE
OneDrive videos are not playing anymore.

### ISSUE THREAD

**Issue by dvasugithub** [cguZZman/plugin.onedrive#40]
The OneDrive videos are not playing anymore.

getting error,

please try again later.
error:
code: bad argument
message: one of the provided arguments is not acceptable.

[kodi.log](https://github.com/cguZZman/plugin.onedrive/files/5104724/kodi.log)

**Comment by pepeusz** [comment]
same here

**Comment by sumit-607wq** [comment]
I'm also facing same issue 
Log file: https://paste.kodi.tv/yeduporuko

**Comment by ooskay** [comment]
Hi,
Same here..

**Comment by devrajdutt** [comment]
Trying to play videos gives a bad argument error for me too.

**Comment by cguZZman** [comment]
This is due to an issue with the API with OneDrive for Business accounts when looking for subtitles. 

In the meantime, you will have to disable the option "Automatically set subtitles from cloud drive" in the addon settings if you want to at least play the videos. This would be the workaround for now.

Anybody is welcome to share a business account for few days to try to solve the issue. Until then, workaround should work

**Comment by devrajdutt** [comment]
Thanks! Disabling subtitles works like a charm

**Comment by ooskay** [comment]
Hi,
I can share. Please give me your email. 

Mine o.oskay@gmail.come

**Comment by cguZZman** [comment]
just sent you a mail. thanks for your help.

**Comment by cguZZman** [comment]
should be fixed in latest version. test again and create a new ticket if the problem persists
